server:
  port: 8100
spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  prefix: /aiden
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviced: eureka-client-ad-sponsor
      strip-prefix: false